61 update datawolf execution step dynamically
IN-CORE/incore-playbook pull request #123
Opened 2023-02-13 18:02 UTC by Rashmil-1999

This PR enables the results to be viewed as soon as the required output datasets are ready after execution from datawolf workflows. To test it, 
- I used SLC playbook's datawolf configuration and ran an analysis in step 3-4. 
- Toggle the running task to view results.
- Wait for the link to be clickable as soon as the requirements are met automatically.

2023-02-13 22:19 UTC, longshuicy requested changes

2023-02-13 22:19 UTC, longshuicy commented on package-lock.json
> +			"version": "0.4.5",
I published 0.4.5 already maybe you can bump everything from now on to 0.4.6

2023-02-13 22:19 UTC, longshuicy commented on src/components/childComponents/table/ViewResultEntryTable.jsx
> +	const checkResultsReady = (listWidgets, currentExecutionDatasetIds) => {
very elegant!

2023-02-13 22:19 UTC, longshuicy commented on src/components/childComponents/table/ViewResultEntryTable.jsx
> +		return requiredDatasetIds.every((reqId) => currentExecutionDatasetIds.includes(reqId));
Sometimes when an step failed, the dataset will display as below
`"0105b539-d201-4eae-f66e-be3fb05d7683": "ERROR",`

SO maybe it's worth to pass the whole dataset object in `execution.datasets` and add one additional check 
```
&& execution.datasets[reqId] !== "ERROR"
```

2023-02-14 15:41 UTC, Rashmil-1999 commented on package-lock.json
> +			"version": "0.4.5",
So, is it okay if I do that in the next PR which is pertaining to the date time format beautification? or I can do this here and keep the same version in the next PR.

2023-02-14 15:44 UTC, Rashmil-1999 commented on src/components/childComponents/table/ViewResultEntryTable.jsx
> +		return requiredDatasetIds.every((reqId) => currentExecutionDatasetIds.includes(reqId));
Okay, got it. I thought "what is the value of the dataset id, is it important or not?" but then just went with the simple approach... Thank you for clearing that up!

2023-02-14 16:08 UTC, longshuicy commented on src/components/childComponents/table/ViewResultEntryTable.jsx
> +		return requiredDatasetIds.every((reqId) => currentExecutionDatasetIds.includes(reqId));
haha sorry i wasn't super clear before

2023-02-14 16:08 UTC, longshuicy commented
Could you resolve the merge conflict?

2023-02-14 19:27 UTC, longshuicy approved these changes

2023-02-14 19:31 UTC, longshuicy commented
Sorry you have to resolve merge conflict again cuz I merged your other PR in

2023-02-14 19:58 UTC, merged