30 robust error handling
IN-CORE/incore-playbook pull request #149
Opened 2023-02-28 16:37 UTC by Rashmil-1999

This PR adds an alert component that takes a message and a status code to be shown. I have only added it to 1 call, if it looks good then I can go ahead and try to add it in other places according to priority.

2023-03-02 20:30 UTC, longshuicy requested changes

2023-03-02 20:30 UTC, longshuicy commented on src/components/childComponents/AlertMessage.jsx
> +	} else if (status !== null) {
Might as well just use "else" here. I'm assuming whenever this Alert Message component is set Open that means something is wrong.

2023-03-02 20:30 UTC, longshuicy commented on src/components/childComponents/AlertMessage.jsx
> +		subMessage = " Error: Forbidden, you don't have enough privileges to run this execution.";
Can you just be more generalized saying `you don't have enough privileges` and leave out the `exeuction` part.

2023-03-02 20:30 UTC, longshuicy commented on src/components/childComponents/RunAnalysis.jsx
> +					/>
If it's possible I would prefer putting this component on the parent component (for each route/page) or even the index root; so this code won't be duplicated else where. 
E.g. with the current setting you have to include <AlertMessage> Again on the "ViewAnalysis" Tab again.

2023-03-06 16:28 UTC, Rashmil-1999 commented on src/components/childComponents/AlertMessage.jsx
> +	} else if (status !== null) {
Yes, it seems fitting. I will update this.

2023-03-06 17:00 UTC, Rashmil-1999 commented on src/components/childComponents/RunAnalysis.jsx
> +					/>
Got it, makes sense, I have added it to the parent component and have only passed it to the run analysis tab for now.

2023-03-06 21:07 UTC, longshuicy commented
hmm i tried to comment out the header when submitting to datawolf. I did get a 401 error but i didn't see any popup..

<img width="742" alt="image" src="https://user-images.githubusercontent.com/13950475/223230890-969bbf1b-c085-46f3-b394-0076f10065bf.png">

2023-03-08 22:03 UTC, longshuicy approved these changes

2023-03-08 22:03 UTC, merged