239 galveston cge region label i vs m different than slc
IN-CORE/incore-playbook pull request #240
Opened 2023-03-29 21:08 UTC by Rashmil-1999

Add dropdown in cge modal for Galveston and also maintain support for other playbooks.

2023-03-30 20:34 UTC, longshuicy commented on CHANGELOG.md
> +- Galveston CGE region label i vs m different than SLC [#239](https://github.com/IN-CORE/incore-playbook/issues/239)
Could you move the changelog to a unrelease

2023-03-30 20:34 UTC, longshuicy commented on src/components/childComponents/graph/CGEBarChart.jsx
> +			if (region.startsWith("R") || (key.startsWith("H") && !/\d$/.test(key))) {
Why "H"?

2023-03-30 20:35 UTC, longshuicy commented on src/components/childComponents/graph/SectorShocksBarChart.jsx
> +			if (dataArr[i][0].startsWith("H") && !/\d$/.test(dataArr[i][0])) {
Same question here why "H"

2023-03-31 13:47 UTC, Rashmil-1999 commented on src/components/childComponents/graph/CGEBarChart.jsx
> +			if (region.startsWith("R") || (key.startsWith("H") && !/\d$/.test(key))) {
it is for the HS1, the reason why I need to make sure this is to avoid any clashes with other labels that might not end in a number. So I make sure that I only pick H**

2023-03-31 14:02 UTC, longshuicy commented on src/components/childComponents/graph/CGEBarChart.jsx
> +			if (region.startsWith("R") || (key.startsWith("H") && !/\d$/.test(key))) {
Ah then can you specify with `HS` then? Because there is also `HH` which has the pattern of `iHH1` vs`mHH1`.

We definitely need a cleaner way to address this after the workshop. Let the team know if you have any ideas~

2023-03-31 16:09 UTC, longshuicy requested changes

2023-03-31 16:09 UTC, longshuicy commented on src/components/childComponents/outputWidgets/CGE.jsx
> +											{console.log("This is here")}
could you remove this console.log

2023-03-31 16:09 UTC, longshuicy commented on src/components/childComponents/outputWidgets/CGE.jsx
> +													title="Employment"
Could you pass the `height="25em"` wherever CGEBarChart is used. Details you can see  
```
<CGEBarChart
	region={region}
	data={cgeHouseholdIncomeContent}
	height="25em"
/>
```

2023-03-31 16:09 UTC, longshuicy commented on src/components/childComponents/outputWidgets/CGE.jsx
> +													title="Employment"
Oh might be nice to add this `yAxisLegend="Million of $"` as well but it might already been hard coded in the CGEBarchart widget, can you double check?

2023-03-31 16:50 UTC, Rashmil-1999 commented on CHANGELOG.md
> +- Galveston CGE region label i vs m different than SLC [#239](https://github.com/IN-CORE/incore-playbook/issues/239)
It is in unreleased right? I don't understand what you are asking me.

2023-03-31 16:50 UTC, Rashmil-1999 commented on src/components/childComponents/graph/CGEBarChart.jsx
> +			if (region.startsWith("R") || (key.startsWith("H") && !/\d$/.test(key))) {
yes agreed. I felt the same. If in the future we get new fields with new variations, then we might have to change this again. HH won't cause issues as the HH pattern starts with i or m so it won't be caught first anyways...

2023-03-31 18:28 UTC, longshuicy commented on src/components/childComponents/graph/SectorShocksBarChart.jsx
> +>>>>>>> develop
could you resolve conflicts here

2023-03-31 19:01 UTC, longshuicy commented on src/components/childComponents/graph/SectorShocksBarChart.jsx
> +>>>>>>> develop
Make sure you use the correct color from develop

2023-03-31 19:02 UTC, longshuicy commented on src/components/childComponents/graph/SectorShocksBarChart.jsx
> +			chartData.push([`${key}_${subKey}`, value, colors[i % 4]]);
This should be 5

2023-03-31 19:25 UTC, longshuicy approved these changes

2023-03-31 19:27 UTC, merged