change table headers to reflect what is received in response
IN-CORE/incore-playbook pull request #286
Opened 2024-02-15 21:35 UTC by Rashmil-1999

Right now when you run it, there will be no visual changes but as soon as the backend is updated to send different keys instead of regular "DS_x" values, the table will reflect what those keys are.

2024-02-16 00:47 UTC, longshuicy approved these changes

2024-02-16 21:28 UTC, longshuicy commented on src/components/childComponents/table/ResultTable.jsx
> +		tableKeys = ["Insignificant", "Moderate", "Extensive", "Complete"];
Can we actually just assume using `Object.keys(fields["by_category"][0])` as both the tableHeader and tableKeys..
Also why would need tableHeader and tableKeys? Shouldn't they just be the same?

2024-02-16 21:30 UTC, longshuicy requested changes
Sorry I just noticed something. Left you a comment

2024-02-19 15:24 UTC, Rashmil-1999 commented
I have set it to use just the table headers.... If you run it now you will not see anything as the backend isn't updated. Once we have that updated, I think it should work...

2024-02-19 15:43 UTC, longshuicy commented on src/components/childComponents/graph/SectorShocksBarChart.jsx
> +			chartData.push([`${key}_${subKey}`, value, colors[i % 4]]);
Hmm why is this change needed?

2024-02-19 15:45 UTC, longshuicy commented on src/components/childComponents/table/ResultTable.jsx
> +	if (fields && ("Insignificant" in fields["by_category"][0])) {
Sorry for nitpicking, I understand you'd like to set a fallback tableHeaders in 115 which is great.
But then why can't you just unpack what the backend send you using `Object.keys(fields["by_category"])` this way we will have the maximum flexibility.

2024-02-19 15:46 UTC, Rashmil-1999 commented on src/components/childComponents/graph/SectorShocksBarChart.jsx
> +			chartData.push([`${key}_${subKey}`, value, colors[i % 4]]);
wait why does this always happen when I pull and update from develop :(

2024-02-19 15:49 UTC, Rashmil-1999 commented on src/components/childComponents/table/ResultTable.jsx
> +	if (fields && ("Insignificant" in fields["by_category"][0])) {
It has one more entry for category which is why I didn't directly use it... I could slice it though which is why I just checked for the presence of the key. let me do the slice one then

2024-02-19 15:49 UTC, Rashmil-1999 commented on src/components/childComponents/graph/SectorShocksBarChart.jsx
> +			chartData.push([`${key}_${subKey}`, value, colors[i % 4]]);
this is some mistake...

2024-02-19 16:00 UTC, longshuicy commented on src/components/childComponents/table/ResultTable.jsx
> +	if (fields && ("Insignificant" in fields["by_category"][0])) {
Ah that make sense. Then forget about it haha.
Let's worry about it if there is a workshop 5 :p

2024-02-19 16:00 UTC, Rashmil-1999 commented
I think everything looks good now...

2024-02-19 17:06 UTC, longshuicy approved these changes

2024-02-19 17:12 UTC, merged