add click to view details of building on map for output widgets
IN-CORE/incore-playbook pull request #295
Opened 2024-02-19 22:51 UTC by Rashmil-1999

View the outputwidgets in step 3-4 for any widget that has a map with buildings on it, if you click any building it will show its detail below in a table.

2024-02-20 21:03 UTC, Rashmil-1999 commented
Fields that a building has:
- `guid`
- `year_built`
- `strctid`
- `struct_typ`
- `ffe_elev`
- `g_elev`
- `max_state`
- `sq_foot`
- `archetype`
- `a_stories`
- `appr_bldg`
- `appr_land`
- `appr_tot`
- `arch_flood`
- `arch_sw`
- `arch_wind`
- `b_stories`
- `broad_occ`
- `bsmt_type`
- `cont_val`
- `csv_sector`
- `csv_val_st`
- `dgn_lvl`
- `dwell_unit`
- `efacility`
- `gsq_foot`
- `major_occ`
- `no_stories`
- `nstra_cst`
- `nstrd_cst`
- `occ_detail`
- `occ_typ2`
- `occ_type`
- `parid`
- `repl_cst`
- `str_cst`
- `str_typ2`

I think the 1st 8-10 factors might be important but we can use this comment to strike out ones we don't need.

And, for Pole damage we have:

- `guid`
- `nodenwid`
- `epf_class`
- `max_state`
- `flow`
- `fltytype`
- `height`
- `spanLength`
- `strctype`
- `utilfcltyc`

2024-02-23 02:12 UTC, longshuicy commented on src/components/childComponents/map/Map.jsx
> +						setSelectedBuilding(json.features[0].properties)
For some reason i have to close the table window then click the next building for the change to reflect. Could you check if that's the case?

2024-02-26 15:44 UTC, Rashmil-1999 commented on src/components/childComponents/map/Map.jsx
> +						setSelectedBuilding(json.features[0].properties)
ohh, let me check that... might have something to do with state update...

2024-02-26 16:18 UTC, Rashmil-1999 commented on src/components/childComponents/map/Map.jsx
> +						setSelectedBuilding(json.features[0].properties)
I don't think that there is any issue. It's just that the response takes time to load from geoserver. Let me see if could set some form of loading icon there to indicate that.

2024-02-26 16:28 UTC, longshuicy commented on src/components/childComponents/map/Map.jsx
> +						setSelectedBuilding(json.features[0].properties)
Ah i see. I guess i was too impatient haha. 
Yes please add a loading spinner (I think you can find an example in this repo as some of the other widget using loading spinner?)

2024-02-28 16:24 UTC, longshuicy commented on src/components/childComponents/outputWidgets/BldgDamage.jsx
> +							// extent={applyTransform(mapConfig.MAP_BOUNDS, getTransform("EPSG:4326", "EPSG:3857"))}
If we are using 4326 could it be apply everywhere? 
Also could you remove the inline comments

2024-02-29 17:28 UTC, longshuicy requested changes
Everything works except i notice the building functionality widgets doesn't show the building layer anymore. Could you look into why?

<img width="1305" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/c9889049-feb1-443b-af51-2fb03ec0a05a">

2024-02-29 17:39 UTC, Rashmil-1999 commented
That only happens with try 9, try 8, try 6, try 4, try 3, try 2, Hurricane Ike 2, Datawolf run... basically, retrofit methods. Its there for Hurricane Ike and before... I don't think something here is causing issues... maybe from geoserver or datawolf?

2024-02-29 17:46 UTC, longshuicy commented
> That only happens with try 9, try 8, try 6, try 4, try 3, try 2, Hurricane Ike 2, Datawolf run... basically, retrofit methods. Its there for Hurricane Ike and before... I don't think something here is causing issues... maybe from geoserver or datawolf?

I see. Let's get your PR merged in first then. We'll look into that later.

2024-02-29 17:46 UTC, longshuicy approved these changes

2024-02-29 17:53 UTC, merged