302 enforce eslint fix through precommit
IN-CORE/incore-playbook pull request #339
Opened 2024-03-04 15:04 UTC by Vismayak

Hi @longshuicy, Rashmil and I went through the eslint and prettierrc config files. I think the only things left would be to run `pre-commit run --all-files` before merging but I wanted to first ensure I did not miss any steps or checks.

2024-03-04 15:21 UTC, longshuicy requested changes
Could you add a changelog entry.

2024-03-04 15:21 UTC, longshuicy commented on .pre-commit-config.yaml
> +            additional_dependencies: ["eslint@7.11.0", "eslint-config-react-app", "babel-eslint@10.1.0"]
We are not using create react app. Is `eslint-config-react-app` still needed?
If needed, could you fix a version?

2024-03-04 15:21 UTC, longshuicy commented on .pre-commit-config.yaml
> +            additional_dependencies: ["eslint@7.11.0", "eslint-config-react-app", "babel-eslint@10.1.0"]
babel-eslint in package json we are using  `"babel-eslint": "^9.0.0"`

2024-03-04 15:21 UTC, longshuicy commented on .pre-commit-config.yaml
> +            additional_dependencies: ["prettier@2.1.2"]
Actually i'm wondering since we have package.json including all the essential libraries, what's the need of additional dependencies?

I looked at Clowder 2 example and didn't find the additional dependencies there
```
- repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "cd frontend && npx eslint --fix src"
        language: system
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c "cd frontend && npx prettier src --write"
        language: system
 ```

2024-03-05 22:14 UTC, Rashmil-1999 approved these changes

2024-03-05 22:15 UTC, Rashmil-1999 commented
Last commit message lol

2024-03-06 16:28 UTC, longshuicy commented
Closing this. Updated in #353

2024-03-06 16:28 UTC, closed without merging