259 adding legend to maps
IN-CORE/incore-playbook pull request #380
Opened 2024-03-13 03:37 UTC by Vismayak

I created the legends for the maps but could I have some input on how I could style it better. Thank you!

2024-03-18 14:19 UTC, longshuicy commented on src/utils/common.js
> +					const legendUrl = `https://incore-dev.ncsa.illinois.edu/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=${layerJSON.LAYERS}&STYLE=${layerJSON.STYLE
Could you remove the hardcoding here? 
We have `https://incore-dev.ncsa.illinois.edu/geoserver/wms` in the `global.js`

2024-03-18 14:20 UTC, longshuicy reviewed
Could you try merge develop back into your branch once you are done with feature updates. I see some diff already in develop but still show as a diff on your branch? Wondering what happened...

2024-03-18 17:46 UTC, Vismayak commented
@longshuicy I have rebased the branch, I think that fixes the problems?

2024-03-18 18:22 UTC, longshuicy commented on src/components/CommunityHazards.jsx
> +									hasLegend={false}
Maybe enable it here too? because we have the capability to view created hazard and it might be good to show them the legend?

2024-03-19 19:06 UTC, Vismayak commented on src/components/CommunityHazards.jsx
> +									hasLegend={false}
I kept it false because when the map has no hazards, it has an empty legend. Should I still keep it?

2024-03-19 20:21 UTC, longshuicy requested changes

2024-03-19 20:21 UTC, longshuicy commented on CHANGELOG.md
> +- Added legend option for maps in the playbook [#259](https://github.com/IN-CORE/incore-playbook/issues/259)
This changelog should go under "unreleased" section.

2024-03-19 20:21 UTC, longshuicy commented on src/utils/common.js
> +export const LegendIcon = createSvgIcon(
Any reason you can't use the .svg directly? 
You can put it under "public" folder?

2024-03-19 20:21 UTC, longshuicy commented on src/components/CompareAnalyses.jsx
> +	const [selectedWidgetName, setSelectedWidgetName] = useState("BldgDamage"); // outputWidgets name
Could you switch this back

2024-03-19 20:21 UTC, longshuicy commented on src/components/childComponents/map/MapCompare.jsx
> +						<h3 className={classes.legendTitle}>Legends</h3>
Can you just use a normal Typography component instead of h3? The word "Legends" is huge

2024-03-19 20:58 UTC, Vismayak commented on src/utils/common.js
> +export const LegendIcon = createSvgIcon(
I mean I don't mind but does it matter? This also allows us to edit the icon if required later with css

2024-03-20 02:38 UTC, longshuicy commented on src/utils/common.js
> +export const LegendIcon = createSvgIcon(
Ah it's just feel like a awkward place. 
If you wish to make your own icon component, could you put it in the "components". 
`Common.js` are places we store common utility functions.

2024-03-21 02:01 UTC, longshuicy approved these changes

2024-03-21 02:01 UTC, merged