change cookie name for auth token
IN-CORE/incore-playbook pull request #383
Opened 2024-03-13 19:53 UTC by Rashmil-1999

This changes the cookie name used for the playbook auth token.

2024-03-13 19:54 UTC, Rashmil-1999 commented
Graph stacked result file was changed by pre-commit

2024-03-14 16:17 UTC, longshuicy requested changes
Code looks good. I can't test it until tomorrow.
One more thing to check, is there any reason why pre-commit is changing this stack graph chart back and forth (i noticed in other PRs too). 
@Vismayak @ylyangtw could you ran this PR see if it change the src/components/childComponents/graph/StackedResult.jsx? If so we need to investigate

2024-03-18 15:14 UTC, longshuicy commented
> Code looks good. I can't test it until tomorrow. One more thing to check, is there any reason why pre-commit is changing this stack graph chart back and forth (i noticed in other PRs too). @Vismayak @ylyangtw could you ran this PR see if it change the src/components/childComponents/graph/StackedResult.jsx? If so we need to investigate

hmm the precommit seems to be correct. I ran a precommit run all files on this PR and there is no diff. 
Hence approving.

2024-03-18 15:14 UTC, longshuicy approved these changes

2024-03-18 15:24 UTC, merged