310 compare interface clean up
IN-CORE/incore-playbook pull request #401
Opened 2024-03-20 14:18 UTC by ylyangtw

Please see this issue https://github.com/IN-CORE/incore-playbook/issues/310 for what should be changed

2024-03-20 21:40 UTC, longshuicy commented on src/components/CompareAnalyses.jsx
> +							<IncoreTitle>Compared Executions:</IncoreTitle>
The alignment is slightly off
<img width="1453" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/534a914c-2322-44b4-acfc-05cb9e9c764d">

- View all toggle probably needs to align with "Completed Analysis"
- "Compare button" probably need to align with "COMPARE ANALYSES"
- Could also add some spaces between these two, it looks a little bit crammed :-(

2024-03-20 21:50 UTC, longshuicy requested changes
<img width="440" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/84e6c897-1584-4bb5-a22b-514ba66d4c76">

Could you also make change to the original data table?

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/graph/SectorShocksBarChartCompare.jsx
> +			chartData.push([`${key}_${subKeyA}`, valueA, colorsA, valueB, colorsB]);
Sector shock looks really nice now!

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/graph/SectorShocksBarChartCompare.jsx
> +						0: { color: "#aededb", labelInLegend: "Execution A" }, // Customize color and name for Data A
Could you use globalConfig["compareKeys"][0] and [1] instead of A and B? There is a slight chance they might want to change that; hence allow the flexibility.

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/map/MapCompare.jsx
> +						Map A
Same A

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/map/MapCompare.jsx
> +						Map B
Same B

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/map/MapCompare.jsx
> -								align="center"
For some reason i think these two table overlapped. Only one table is showing right now
<img width="1447" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/fc995cb4-2395-4a21-8260-a17d64daa0f5">

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/map/MapCompare.jsx
> +										<TableCell align="right">
Also if you have time, could you stretch the map to align with tables? Right now there are white space at each side
<img width="1779" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/3347d1e4-0dd1-4ae8-953d-ecb0a45afe65">

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/table/CGEResultsTableCompare.jsx
> +								Difference between A and B
Same hardcode A, B

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/graph/CGEBarChartCompare.jsx
> -					bars: "horizontal",
For the legend, is it possible to add a () around the execution name? It's a bit hard to read
<img width="243" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/0907a29d-853f-4d2c-aa46-b5e231ea78a2">

2024-03-20 21:50 UTC, longshuicy commented on src/components/childComponents/graph/CGEBarChartCompare.jsx
> -					bars: "horizontal",
Also is it possible that the chart and the table take the full div?

2024-03-20 21:55 UTC, longshuicy commented on src/components/childComponents/map/MapCompare.jsx
> +										<TableCell align="right">
@ylyangtw actually never mind this one. It's addressed in another PR.

2024-03-20 22:05 UTC, longshuicy commented
FYI you can use the ```import { IncoreFootNote } from "../../styledComponents/IncoreFootNote";``` component for prompt if it makes your life easier.

2024-03-21 14:05 UTC, ylyangtw commented on src/components/CompareAnalyses.jsx
> +							<IncoreTitle>Compared Executions:</IncoreTitle>
Good catch. I adjusted the components and margin

2024-03-21 14:06 UTC, ylyangtw commented on src/components/childComponents/graph/CGEBarChartCompare.jsx
> -					bars: "horizontal",
Fixed all map issues. chat and table are taking full div now

2024-03-21 14:06 UTC, ylyangtw commented on src/components/childComponents/graph/CGEBarChartCompare.jsx
> -					bars: "horizontal",
I added [ ] to the legend instead. () looks like some comments?

2024-03-21 16:48 UTC, longshuicy commented on src/components/childComponents/graph/CGEBarChartCompare.jsx
> -					bars: "horizontal",
looks very nice!!

2024-03-21 17:01 UTC, longshuicy approved these changes

2024-03-21 17:02 UTC, merged