fixed table headers added to multiple tables.
IN-CORE/incore-playbook pull request #462
Opened 2024-04-04 20:32 UTC by Rashmil-1999

Tables to Check would be Building Damage, Functionality, Population dislocation and their respective comparisons and Retrofit summary table.

2024-04-04 21:00 UTC, longshuicy requested changes
Overall looks good. Just some minor suggestions for change.

2024-04-04 21:00 UTC, longshuicy commented on src/components/childComponents/table/BldgDamageTable.jsx
> +			<Table
When scrolling the View percentage got scrolled up and has no way to get to it. Maybe move that outside the table container.
<img width="1247" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/1d778599-0dc9-48b8-b26a-1f2fd65e0790">
<img width="1265" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/259bdd02-d978-4322-b003-7f20ff37fea2">

2024-04-04 21:00 UTC, longshuicy commented on src/components/childComponents/table/FunctionalityTable.jsx
> +		<TableContainer className={classes.tableContainer}>
same with percent and % of buildings
<img width="911" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/94acf514-2121-40c6-87ab-b84a2ab5e277">

2024-04-04 21:00 UTC, longshuicy commented on src/components/childComponents/table/FunctionalityTable.jsx
> +		<TableContainer className={classes.tableContainer}>
Actually you can look at the comparison table. That seems to be correct.
<img width="1778" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/168dbad2-a59d-4fdf-a487-f719cb38ef87">

2024-04-04 21:00 UTC, longshuicy commented on src/components/childComponents/table/HuaResultsTable.jsx
> +				<TableContainer className={classes.tableContainer}>
Same for this table and comparison, you might want to change the header cell color to not be transparent. When scrolling some of the those become see through.

<img width="929" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/9484edf7-7f53-4d87-8375-69ff4c538abc">

2024-04-04 21:00 UTC, longshuicy commented on src/components/childComponents/RetrofitStrategySummary.jsx
> +					>
The header color disappeared for some reason. Also the border becomes so thick. Could you compare what's on production.

prod:
<img width="1269" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/65f7238c-9adc-46bd-9f64-e5a7b0a9e6b6">


Your PR:
<img width="1271" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/5af62f92-eaa8-4f93-8370-856e0dab0b41">

2024-04-04 21:08 UTC, Rashmil-1999 commented on src/components/childComponents/table/FunctionalityTable.jsx
> +		<TableContainer className={classes.tableContainer}>
This one was like this I didn't touch anything else. I can make it look like the compare. Do you want me to do that? That involves some changes in table cell movements and stuff..

2024-04-04 21:32 UTC, longshuicy commented on src/components/childComponents/table/FunctionalityTable.jsx
> +		<TableContainer className={classes.tableContainer}>
I see. could you make them the same?

2024-04-04 21:45 UTC, Rashmil-1999 commented on src/components/childComponents/RetrofitStrategySummary.jsx
> +					>
Done @longshuicy

2024-04-05 17:14 UTC, longshuicy approved these changes
I slightly added a bit container height for the population and functionality table. Approving.

2024-04-05 17:14 UTC, merged