71 connect step status with maestro services endpoint
IN-CORE/incore-playbook pull request #80
Opened 2022-12-09 22:49 UTC by Rashmil-1999

This PR connects the step change with the new maestro service PR [#30](https://github.com/IN-CORE/maestro-service/pull/30). For this PR to work, one needs to run maestro locally as currently, it points to a local host, and update step status works with the new Maestro endpoint.

2022-12-10 02:58 UTC, longshuicy commented on src/actions/steps.js
> +    let endpoint = `http://localhost:8000/maestro/steps/${stepId}/${substepId}`
can you remove the hardcoding here and switch back to line 16?

2022-12-10 02:59 UTC, longshuicy commented on src/actions/steps.js
> +    let endpoint = `http://localhost:8000/maestro/steps/${stepId}/${substepId}?status=${status}`
same here

2022-12-10 02:59 UTC, longshuicy commented on src/actions/steps.js
> +			"x-auth-userinfo": `{"preferred_username":"rmp6"}`
Same here

2022-12-10 03:01 UTC, longshuicy commented on src/components/childComponents/UserInfo.jsx
> +		console.log("TODO: Implement save functionality")
this is addressed in the other PR which has significant change... just wait for that to be merged and you might need to update this file. sorry!

2022-12-10 03:02 UTC, longshuicy commented on src/globals.js
> +globals["maestroServiceBase"] = `${hostname}/maestro`;
you can point this to one of the testbed, maybe try `${hostname}/maestro/galveston`

2022-12-10 03:04 UTC, longshuicy commented on src/reducers/stepsReducer.js
> +const step_strings = [
can you use the step_strings to initiate the `defaultState` to reduce duplicating?

2022-12-10 03:10 UTC, longshuicy commented on src/reducers/stepsReducer.js
> +            switch (action.step_id) {
can this part be a little bit smarter? I haven't tested it but maybe instead of switch/case, just directly return 
```
case "UPDATE_STEP":
        return {... state,  [action.step_id]: action.step}
```

2022-12-10 03:11 UTC, longshuicy commented on src/routes.js
>  	"/goal-objective-result": {
we need to add step status to every single substep page. Are you planning to do that in a separate task?
It's still worth to at least pass in that as props in every route here.

2022-12-10 03:12 UTC, longshuicy requested changes
I am reiterate the part that"we need to add step status to every single substep page."  in the PR comments so just we don't forget.

2022-12-12 16:36 UTC, Rashmil-1999 commented on src/actions/steps.js
> +    let endpoint = `http://localhost:8000/maestro/steps/${stepId}/${substepId}`
The issue is that the default value it uses it that of dev instance.

2022-12-12 16:36 UTC, Rashmil-1999 commented on src/actions/steps.js
> +    let endpoint = `http://localhost:8000/maestro/steps/${stepId}/${substepId}`
But we don't have it deployed yet so had to keep this line to test it.

2022-12-12 16:56 UTC, Rashmil-1999 commented on src/reducers/stepsReducer.js
> +const step_strings = [
Oops, I don't use that anymore, I need to remove that.

2022-12-12 16:59 UTC, Rashmil-1999 commented on src/reducers/stepsReducer.js
> +            switch (action.step_id) {
using strings gave me a state update issue saying I can't update the state value directly. I tried a bunch of other stuff too which is why I ended up with this. I can try this suggestion and see what happens.

2022-12-12 17:01 UTC, Rashmil-1999 commented on src/routes.js
>  	"/goal-objective-result": {
I added it to all the finalized components. I didn't add anything in `StepTmpInfo` as it was simply a placeholder for another final component I thought.

2022-12-12 17:08 UTC, Rashmil-1999 commented on src/reducers/stepsReducer.js
> +            switch (action.step_id) {
I didn't know that wrapping a string in square brackets will help solve the state mutation issue. Thank you so much! This works now.

2022-12-14 19:43 UTC, longshuicy approved these changes

2022-12-14 19:43 UTC, longshuicy commented on src/actions/steps.js
> +		// });
you might want to remove this blob so it doesn't have your username in the code :p

2022-12-14 19:46 UTC, longshuicy commented on src/actions/steps.js
> +		// });
removed for you

2022-12-14 20:46 UTC, merged