77 main step status aggregated from each substeps status
IN-CORE/incore-playbook pull request #85
Opened 2022-12-14 17:09 UTC by Rashmil-1999

This PR adds the main step status based on the aggregated substeps. This PR depends on PR [#80](https://github.com/IN-CORE/incore-playbook/pull/80)

2022-12-15 18:27 UTC, longshuicy requested changes

2022-12-15 18:27 UTC, longshuicy commented on src/components/childComponents/navigation/HeaderWithMenu.jsx
> +			}
this logic seems a little bit hard for me to understand. Can you add a few inline comments to elaborate?

2022-12-15 18:27 UTC, longshuicy commented on src/components/childComponents/navigation/HeaderWithMenu.jsx
> +	let treeData = [
A lot of the information in the treeData seems to overlapping the the information in the "router" and the reducers; wondering if we can have a more centralized place to innitialize them

2022-12-15 18:27 UTC, longshuicy commented on src/components/childComponents/navigation/HeaderWithMenu.jsx
> +					status: "in_progress",
can we just initialize everything as "pending"

2022-12-15 18:27 UTC, longshuicy commented on src/components/childComponents/navigation/HeaderWithMenu.jsx
> +	const greenCheckIcon = <CheckCircleIcon style={{ color: "green" }} />;
can you name them "completedCheckIcon" and "pendingCheckIcon"; and use the color hex i shared with you the other day?

2022-12-16 16:08 UTC, Rashmil-1999 commented on src/components/childComponents/navigation/HeaderWithMenu.jsx
> +			}
Yes sure.

2022-12-16 16:18 UTC, Rashmil-1999 commented on src/components/childComponents/navigation/HeaderWithMenu.jsx
> +	let treeData = [
Yes, I believe that could be done. It would seem like a code optimization task. I feel it would be better if you can create a separate task for this. What do you think of it?

2022-12-16 16:19 UTC, Rashmil-1999 commented on src/components/childComponents/navigation/HeaderWithMenu.jsx
> +					status: "in_progress",
ohh this, I had actually initiated to pending. I wanted to see changes in the initial load of the component. That is why I changed those values and forgot to reset them to the original value. I will make the necessary changes now.

2022-12-16 16:21 UTC, Rashmil-1999 commented on src/components/childComponents/navigation/HeaderWithMenu.jsx
> +	const greenCheckIcon = <CheckCircleIcon style={{ color: "green" }} />;
Yes, I will do that now.

2022-12-16 23:07 UTC, longshuicy commented
There is one bug i noticed but it doesn't affect the user experience (I will document it in another PR)
when logout it's calling the GET /steps which is not neccesary and cause a 401 error on the console
<img width="477" alt="image" src="https://user-images.githubusercontent.com/13950475/208203108-6371a5b0-4ee0-459a-8188-686bfc8b795c.png">

2022-12-16 23:08 UTC, longshuicy approved these changes
brief testing works. It's hard to review the code itself since there are too many linting change :-(

Will open new bug issues if after merging we notice anything

2022-12-16 23:14 UTC, merged